INSERT INTO Ingredient (Name, Amount, Unit, RecipeId)
VALUES ('Spaghetti', 1, 'lb', 1),
       ('Pancetta', 4, 'oz', 1),
       ('Garlic', 3, 'cloves', 1),
       ('Eggs', 3, '', 1),
       ('Parmesan cheese', 1, 'cup', 1),
       ('Black pepper', 1/2, 'tsp', 1),
       ('Asparagus', 1, 'lb', 2),
       ('Salmon fillets', 4, '', 2),
       ('Olive oil', 2, 'tbsp', 2),
       ('Lemon zest', 1, 'tsp', 2),
       ('Salt', 1/2, 'tsp', 2),
       ('Black pepper', 1/2, 'tsp', 2),
       ('Beef', 1, 'lb', 3),
       ('Onion', 1, 'medium', 3),
       ('Mushrooms', 8, 'oz', 3),
       ('Beef broth', 1, 'cup', 3),
       ('Sour cream', 1/2, 'cup', 3),
       ('Dijon mustard', 1, 'tbsp', 3),
       ('Worcestershire sauce', 1, 'tbsp', 3),
       ('Arborio rice', 1, 'cup', 4),
       ('Chicken broth', 4, 'cups', 4),
       ('Olive oil', 2, 'tbsp', 4),
       ('Onion', 1, 'medium', 4),
       ('White wine', 1/2, 'cup', 4),
       ('Mushrooms', 8, 'oz', 4),
       ('Parmesan cheese', 1/2, 'cup', 4),
       ('Parsley', 1/4, 'cup', 4);

